language: node_js
node_js: '9'
services:
- postgresql
before_script:
- psql -c 'create database palette_picker_test;' -U postgres
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: ZrF+r/wW9AlzGoXLg7eGoFVIu/Iug0EWYja8FEYtoKDNssb3n1l+KxjitBvdDOE2mZ1ncKIiEJmAzMeKwkD28NLrsnTTO6EFI5om6z0i36R0tpqtWBLSmuxHohJYmi3oFKFqvp2rKQzK9RFCkXo4UBuBd9ZtBZcJm8c4CzcKpYQnFpszFuNywjBS5wh9Nm9n7YdbCBdIUv7lIl1OnB+IfCdgCjoOd4uCJOSST2XbMzwxYGjNrm0x/KBtj/6ly2ZxtQdrFSwc6mITFkJEkpsti//pq1i/FfYjmi3Jn6dun4qGI75uvf6zgYm7I8i7/5CV/r4glHuiF+azv9fGga9bkwVuwyeNmanbt9gfNxVK1BGMvwYpzGDdK+FRmPYlYwDLXlxYsmPNC0NE4BxUJqeYty82JzYNfxDXzms7ZaeVMSUK7Npc7IWX1u6eN5Hg2sXDwhbAGpcjFbN3pgoFrralpj/mViMfZ93zo7Las1GXmuW08UIQF7cQP2hK9w1rjun0I/w1gE/UNo9ZFStCttkpSnkBUVBBLOW7mz+OEWfsJTMjRKZIMZHrPVwtKZZInXp0VCIUmSG7yfbU4Sbwdp5GnMxtb5LI79U8JW7n7MiL0U9IhoB/eE2JRgxh7JDasXDSJgnDSo0yz/J7LgmVMnOfc3/DQnf7hW9uUx2G1rGzICA=
